### ISSUE TITLE
Sync fails for media directly added to the tweet

### ISSUE THREAD

**Issue by nfrankel** [klausi/mastodon-twitter-sync#69] opened 2023-02-01 18:44 UTC
[This tweet](https://twitter.com/nicolas_frankel/status/1620423298894172160) cannot be synchronized because it contains a GIF. I already had the same issue when I added an image directly to the tweet.

The error is:

```
Error posting toot to Mastodon: Error {
    context: "Failed downloading attachment ",
    source: reqwest::Error {
        kind: Builder,
        source: RelativeUrlWithoutBase,
    },
}
```

**Comment by klausi** [comment] 2023-02-02 08:51
Thanks for reporting, I think this is a duplicate of #63

**Closed by klausi** 2023-02-02 08:51 UTC

**Comment by nfrankel** [comment] 2023-02-02 08:52
Sorry, I checked but I didn't see it.
